<script setup>
useHead({
    title: 'Disclaimer'
})
</script>
<template>
    <div>
        <div class="text-base mt-3 ci flex flex-col gap-4">
            <div>
                <h1>Disclaimer</h1>
            </div>

            <h2>1. General Information</h2>
            <div>
                Catsentence is a multi-platform interactive learning application designed to enhance listening and
                comprehension skills. While we strive to provide accurate and useful content, we do not guarantee the
                completeness, accuracy, or reliability of the information generated by the app.
            </div>

            <h2>2. Educational Purpose Only</h2>
            Catsentence is intended for educational and personal learning purposes. The app should not be used as a
            substitute for professional language interpretation, transcription, or translation services. Users should
            verify any information before relying on it.

            <h2>3. Third-Party Content</h2>
            <div>
                Catsentence may process content from third-party platforms, including but not limited to YouTube and
                other media sources. We do not own, control, or endorse third-party content, and all copyrights remain
                with their respective owners. If you believe any content infringes on intellectual property rights,
                please contact the original content provider.
            </div>

            <h2>4. User Responsibility</h2>
            <div>
                Users are responsible for their own interactions and use of the app. Catsentence is not liable for any
                misinterpretation of content, misuse of features, or any consequences resulting from its usage. Users
                must comply with all applicable platform policies and community guidelines.
            </div>

            <h2>5. Changes and Updates</h2>
            <div>
                This disclaimer may be modified at any time without prior notice. Continued use of the app after changes
                implies acceptance of the updated terms.
            </div>
        </div>
    </div>
</template>
<style scoped>
h2 {
    font-size: 20px;
    margin-top: 1rem;
    color: #00AA45;
}

h1 {
    font-size: 24px;
    margin-top: 1rem;
    color: #00AA45;
}

ul {
    list-style-type: disc;
    /* Ensures bullet points */
    padding-left: 20px;
    /* Adds spacing for indentation */
}
</style>